name: cli tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and test bin/ms with AL
    runs-on: ubuntu-latest 

    steps:
    - uses: 0xADE1A1DE/AssemblyLine@main

    - name: Install dependencies
      run: sudo apt install -y lcov python3 python3-pip nasm
    - run: pip3 install plotly lcov_cobertura

    - uses: actions/checkout@v3

    - name: C checks
      run: make clean check

