name: TS Code formatting

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  formatting-check:
    name: TS Prettier formatting check
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: 0xADE1A1DE/AssemblyLine@dev

    - uses: actions/checkout@v3

    - name: Check
      run: npm install && npm run formatting

    - name: Fail fast?!
      if: failure()
      run: |
        echo "Some files failed the formatting checks!"; exit 1

  lint:
    name: TS Lint check
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: 0xADE1A1DE/AssemblyLine@dev
    
    - uses: actions/checkout@v3
  
    - name: Check
      run: npm install && npm run lint
  
    - name: Fail fast?!
      if: failure()
      run: |
        echo "Some files failed the linting checks!"; exit 1
